language: swift
osx_image: xcode10.2

before_install:
  - gem install cocoapods
  - pod update

# Build the main app, which happens to depend on the other two targets.
script: xcodebuild -workspace iina.xcworkspace -scheme iina

notifications:
  email: false
